config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do

	root 'registration#new'

	scope :registro, as: 'registro' do
		get 'nuevo' => 'registration#new'
		get 'exito' => 'registration#success'
		post 'crear' => 'registration#create'
		post 'encuesta' => 'registration#survey'
	end

	scope 'promociones' do
		get 	'/', 					to: 'promotions#index', 		as: 'promotions'
		get 	'/:id', 				to: 'promotions#show', 			as: 'promotion'
		post 	'/:id', 				to: 'promotions#claim'
		get 	'/:id/ganador',	to: 'promotions#winner', 		as: 'promotion_winner'
	end

	scope 'contacto', as: 'contact' do
		get '/', to: 'messages#new'
		post '/', to: 'messages#create'
	end

	get '/preguntas-frecuentes',	 to: 'static_pages#faq'
	get '/terminos',					 to: 'static_pages#site_terms'
	get '/quienes-somos',			 to: 'static_pages#about'
	get '/instrucciones',			 to: 'static_pages#instructions'
	
	devise_for :agents, path_names: {
 		sign_in: 'acceder', 
 		sign_out: 'salir', 
 		password: 'contrasena', 
 		confirmation: 'confirmacion', 
 		unlock: 'desbloquear', 
 		registration: 'registro', 
 		sign_up: 'nueva-cuenta'
	}

	authenticate :agent, lambda { |a| a.approved? } do
		mount Sidekiq::Web => 'admin/sidekiq'
	end

	get '/admin', to: redirect('admin/dashboard/index')

	namespace :admin do
		resources :agents, except: [:new, :create]
		resources :business_branches
		resources :businesses do
			member do
				post 'upload_logo'
				delete 'delete_logo'
			end
		end
		resources :coupon_winners
		resources :coupons do
			member do
				get 'preview'
				post 'upload_image'
				delete 'delete_image'
			end
		end
		get 'dashboard/index'
		resources :emails
		resources :emails_sent
		resources :project_updates
		resources :states, except: [:new, :create, :destroy]
		resources :surveys
		resources :surveys_dispensed
		resources :users
	end

	match '*path', to: redirect('/404'), via: :all

end

app/models/admin/survey.rb
class Admin::Survey < ActiveRecord::Base
	self.table_name = "surveys"
	
	has_many :surveys_dispensed, dependent: :destroy

	AUDIENCE_OPT = %w(users businesses)

	validates :purpose, 
		presence: {
			message: ErrorMsg::MSG[:empty_field]
		}

	validates :audience, 
		presence: {
			message: ErrorMsg::MSG[:empty_field]
		},
		inclusion: {
			in: AUDIENCE_OPT,
			message: ErrorMsg::MSG[:invalid_option]
		}

	validates :template_name, 
		presence: {
			message: ErrorMsg::MSG[:empty_field]
		}

end

app/controllers/admin/surveys_controller.rb
class Admin::SurveysController < ApplicationController

	before_action :authenticate_agent!
	before_action :authorize_agent!
	before_action :set_survey, only: [:show, :edit, :update, :destroy]

	# GET /surveys
	# GET /surveys.json
	def index
		@surveys = Admin::Survey.order(:id)
	end

	# GET /surveys/1
	# GET /surveys/1.json
	def show
	end

	# GET /surveys/new
	def new
		@survey = Admin::Survey.new
	end

	# GET /surveys/1/edit
	def edit
	end

	# POST /surveys
	# POST /surveys.json
	def create
		@survey = Admin::Survey.new(survey_params)

		respond_to do |format|
			if @survey.save
				format.html { redirect_to @survey, notice: 'La encuesta se creó con éxito.' }
				format.json { render :show, status: :created, location: @survey }
			else
				format.html { render :new }
				format.json { render json: @survey.errors, status: :unprocessable_entity }
			end
		end
	end

	# PATCH/PUT /surveys/1
	# PATCH/PUT /surveys/1.json
	def update
		respond_to do |format|
			if @survey.update(survey_params)
				format.html { redirect_to @survey, notice: 'La encuesta se actualizó con éxito.' }
				format.json { render :show, status: :ok, location: @survey }
			else
				format.html { render :edit }
				format.json { render json: @survey.errors, status: :unprocessable_entity }
			end
		end
	end

	# DELETE /surveys/1
	# DELETE /surveys/1.json
	def destroy
		@survey.destroy
		respond_to do |format|
			format.html { redirect_to admin_surveys_url, notice: 'La encuesta se eliminón con éxito.' }
			format.json { head :no_content }
		end
	end

	private
		# Use callbacks to share common setup or constraints between actions.
		def set_survey
			@survey = Admin::Survey.where(id: params[:id]).first
			notice = "La encuesta buscada no se encontró."
			redirect_to(admin_surveys_url, notice: notice) if @survey.nil?
		end

		# Never trust parameters from the scary internet, only allow the white list through.
		def survey_params
			params.require(:admin_survey).permit(:purpose, :audience, :template_name)
		end
end

app/helpers/admin/surveys_helper.rb
module Admin::SurveysHelper
end

app/views/admin/surveys/_form.html.haml
= form_for @survey do |f|
	.row
		.column.medium-12
			- if @survey.errors.any?
				#error_explanation
					%h2= "#{pluralize(@survey.errors.count, "error")} prohibited this survey from being saved:"
					%ul
						- @survey.errors.full_messages.each do |msg|
							%li= msg
	.row
		.column.medium-5
			.field
				= f.label :purpose, 'Propósito'
				= f.text_field :purpose
		.column.medium-3		
			.field
				= f.label :audience, 'Audiencia'
				= f.select :audience, 
					Admin::Survey::AUDIENCE_OPT.each { |opt| [opt] }, 
					include_blank: true
		.column.medium-4			
			.field
				= f.label :template_name, 'Plantilla (partial)'
				= f.text_field :template_name
		.column.medium-12	
			%br/
			.actions
				= f.submit 'Guardar', class: 'button'

app/views/admin/surveys/edit.html.haml
= render layout: './admin/admin_base' do
	%h2.title Editar Encuesta

	= render 'form'

	= link_to 'Mostrar', edit_admin_survey_path(@survey)
	\|
	= link_to 'Listado', admin_surveys_path

app/views/admin/surveys/index.html.haml
= render layout: './admin/admin_base' do
	%h2.title Listado de Encuestas

	%table
		%thead
			%tr
				%th Id
				%th Propósito
				%th Audiencia
				%th Plantilla (partial)
				%th
				%th
				%th

		%tbody
			- @surveys.each do |survey|
				%tr
					%td= survey.id
					%td= survey.purpose
					%td= survey.audience
					%td= survey.template_name
					%td= link_to 'Mostrar', admin_survey_path(survey)
					%td= link_to 'Editar', edit_admin_survey_path(survey)
					%td= link_to 'Eliminar', admin_survey_path(survey), :method => :delete, 
						:data => { :confirm => '¿Está seguro?' }

	%br

	= link_to 'Nueva Encuesta', new_admin_survey_path

app/views/admin/surveys/new.html.haml
= render layout: './admin/admin_base' do
	%h2.title Nueva Encuesta

	= render 'form'

	= link_to 'Listado', admin_surveys_path

app/views/admin/surveys/show.html.haml
= render layout: './admin/admin_base' do
	%h2.title Encuesta

	%p
		%b Id:
		= @survey.id
	%p
		%b Propósito:
		= @survey.purpose
	%p
		%b Audiencia:
		= @survey.audience
	%p
		%b Plantilla (partial):
		= @survey.template_name

	= link_to 'Editar', edit_admin_survey_path(@survey)
	\|
	= link_to 'Listado', admin_surveys_path