config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do

	root 'registration#new'

	scope :registro, as: 'registro' do
		get 'nuevo' => 'registration#new'
		get 'exito' => 'registration#success'
		post 'crear' => 'registration#create'
		post 'encuesta' => 'registration#survey'
	end

	scope 'promociones' do
		get 	'/', 					to: 'promotions#index', 		as: 'promotions'
		get 	'/:id', 				to: 'promotions#show', 			as: 'promotion'
		post 	'/:id', 				to: 'promotions#claim'
		get 	'/:id/ganador',	to: 'promotions#winner', 		as: 'promotion_winner'
	end

	scope 'contacto', as: 'contact' do
		get '/', to: 'messages#new'
		post '/', to: 'messages#create'
	end

	get '/preguntas-frecuentes',	 to: 'static_pages#faq'
	get '/terminos',					 to: 'static_pages#site_terms'
	get '/quienes-somos',			 to: 'static_pages#about'
	get '/instrucciones',			 to: 'static_pages#instructions'
	
	devise_for :agents, path_names: {
 		sign_in: 'acceder', 
 		sign_out: 'salir', 
 		password: 'contrasena', 
 		confirmation: 'confirmacion', 
 		unlock: 'desbloquear', 
 		registration: 'registro', 
 		sign_up: 'nueva-cuenta'
	}

	authenticate :agent, lambda { |a| a.approved? } do
		mount Sidekiq::Web => 'admin/sidekiq'
	end

	get '/admin', to: redirect('admin/dashboard/index')

	namespace :admin do
		resources :agents, except: [:new, :create]
		resources :business_branches
		resources :businesses do
			member do
				post 'upload_logo'
				delete 'delete_logo'
			end
		end
		resources :coupon_winners
		resources :coupons do
			member do
				get 'preview'
				post 'upload_image'
				delete 'delete_image'
			end
		end
		get 'dashboard/index'
		resources :emails
		resources :emails_sent
		resources :project_updates
		resources :states, except: [:new, :create, :destroy]
		resources :surveys
		resources :surveys_dispensed
		resources :users
	end

	match '*path', to: redirect('/404'), via: :all

end

app/controllers/admin/emails_sent_controller.rb
class Admin::EmailsSentController < ApplicationController
	before_action :authenticate_agent!
	before_action :authorize_agent!
	before_action :set_email_sent, only: [:show, :edit, :update, :destroy]

	# GET /emails_sent
	# GET /emails_sent.json
	def index
		@emails_sent = Admin::EmailSent.all
	end

	# GET /emails_sent/1
	# GET /emails_sent/1.json
	def show
	end

	# GET /emails_sent/new
	def new
		@email_sent = Admin::EmailSent.new
	end

	# GET /emails_sent/1/edit
	def edit
	end

	# POST /emails_sent
	# POST /emails_sent.json
	def create
		@email_sent = Admin::EmailSent.new(email_sent_params)

		respond_to do |format|
			if @email_sent.save
				format.html { redirect_to @email_sent, notice: 'Email sent was successfully created.' }
				format.json { render :show, status: :created, location: @email_sent }
			else
				format.html { render :new }
				format.json { render json: @email_sent.errors, status: :unprocessable_entity }
			end
		end
	end

	# PATCH/PUT /emails_sent/1
	# PATCH/PUT /emails_sent/1.json
	def update
		respond_to do |format|
			if @email_sent.update(email_sent_params)
				format.html { redirect_to @email_sent, notice: 'Email sent was successfully updated.' }
				format.json { render :show, status: :ok, location: @email_sent }
			else
				format.html { render :edit }
				format.json { render json: @email_sent.errors, status: :unprocessable_entity }
			end
		end
	end

	# DELETE /emails_sent/1
	# DELETE /emails_sent/1.json
	def destroy
		@email_sent.destroy
		respond_to do |format|
			format.html { redirect_to admin_emails_sent_url, notice: 'Email sent was successfully destroyed.' }
			format.json { head :no_content }
		end
	end

	private
		# Use callbacks to share common setup or constraints between actions.
		def set_email_sent
			@email_sent = Admin::EmailSent.where(id: params[:id]).first
			notice = "El correo enviado buscado no se encontró"
			redirect_to(admin_emails_sent_url, notice: notice) if @email_sent.nil?
		end

		# Never trust parameters from the scary internet, only allow the white list through.
		def email_sent_params
			params.require(:admin_email_sent).permit(
				:email_id, 
				:user_id, 
				:sent, 
				:status, 
				:attempts, 
				:response,
				:metadata
			)
		end
end

app/helpers/admin/emails_sent_helper.rb
module Admin::EmailsSentHelper
end

app/views/admin/emails_sent/_form.html.haml
= form_for @email_sent do |f|
	.row
		.column.medium-12
			- if @email_sent.errors.any?
				#error_explanation
					%h2= "#{pluralize(@email_sent.errors.count, "error")} prohibited this email_sent from being saved:"
					%ul
						- @email_sent.errors.full_messages.each do |msg|
							%li= msg

	.row
		.column.medium-10
			.field
				= f.label :email_id, 'Correo'
				= f.text_field :email_id
		.column.medium-2
			.field
				= f.label :sent, 'Enviado?'
				= f.check_box :sent
		.column.medium-4
			.field
				= f.label :user_id, 'Usuario'
				= f.text_field :user_id
		.column.medium-4
			.field
				= f.label :status, 'Estatus'
				= f.text_field :status
		.column.medium-4		
			.field
				= f.label :attempts, 'Intentos'
				= f.number_field :attempts
		.column.medium-12		
			.field
				= f.label :response, 'Respuesta'
				= f.text_area :response, rows: 10
			.actions
				= f.submit 'Guardar', class: 'button'

app/views/admin/emails_sent/edit.html.haml
= render layout: './admin/admin_base' do
	%h2.title Editar Correo Enviado

	= render 'form'

	= link_to 'Mostrar', edit_admin_email_sent_path(@email_sent)
	\|
	= link_to 'Listado', admin_emails_sent_path

app/views/admin/emails_sent/index.html.haml
= render layout: './admin/admin_base' do
  %h2.title Listado de Correos Enviados

  %table
    %thead
      %tr
        %th Id
        %th Correo
        %th Usuario
        %th Enviado?
        %th Estatus
        %th Intentos
        %th Respuestas?
        %th
        %th
        %th

    %tbody
      - @emails_sent.each do |email_sent|
        %tr
          %td= email_sent.id
          %td= link_to email_sent.email.purpose, admin_email_path(email_sent.email.id)
          %td= link_to email_sent.user.email, admin_user_path(email_sent.user.id)
          %td= email_sent.sent? ? 'Si' : 'No'
          %td= email_sent.status
          %td= email_sent.attempts
          %td= email_sent.response ? 'Si' : 'No'
          %td= link_to 'Mostrar', admin_email_sent_path(email_sent)
          %td= link_to 'Editar', edit_admin_email_sent_path(email_sent)
          %td= link_to 'Eliminar', admin_email_sent_path(email_sent), :method => :delete, :data => { :confirm => '¿Está seguro?' }

  %br

  = link_to 'Nuevo Correo Enviado', new_admin_email_sent_path

app/views/admin/emails_sent/new.html.haml
= render layout: './admin/admin_base' do
	%h2.title Nuevo Correo Enviado

	= render 'form'

	= link_to 'Listado', admin_emails_sent_path

app/views/admin/emails_sent/show.html.haml
= render layout: './admin/admin_base' do
	%h2.title Correo Enviado

	%p
		%b Id:
		= @email_sent.id
	%p
		%b Correo:
		= link_to @email_sent.email.purpose, admin_email_path(@email_sent.email.id)
	%p
		%b Usuario:
		= link_to @email_sent.user.email, admin_user_path(@email_sent.user.id)
	%p
		%b Enviado?:
		= @email_sent.sent
	%p
		%b Estatus:
		= @email_sent.status
	%p
		%b Intentos:
		= @email_sent.attempts
	%p
		%b Respuesta:
		%pre
			= JSON.pretty_generate(@email_sent.response) if @email_sent.response

	%br/
	= link_to 'Editar', edit_admin_email_sent_path(@email_sent)
	\|
	= link_to 'Listado', admin_emails_sent_path