config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do

	root 'registration#new'

	scope :registro, as: 'registro' do
		get 'nuevo' => 'registration#new'
		get 'exito' => 'registration#success'
		post 'crear' => 'registration#create'
		post 'encuesta' => 'registration#survey'
	end

	scope 'promociones' do
		get 	'/', 					to: 'promotions#index', 		as: 'promotions'
		get 	'/:id', 				to: 'promotions#show', 			as: 'promotion'
		post 	'/:id', 				to: 'promotions#claim'
		get 	'/:id/ganador',	to: 'promotions#winner', 		as: 'promotion_winner'
	end

	scope 'contacto', as: 'contact' do
		get '/', to: 'messages#new'
		post '/', to: 'messages#create'
	end

	get '/preguntas-frecuentes',	 to: 'static_pages#faq'
	get '/terminos',					 to: 'static_pages#site_terms'
	get '/quienes-somos',			 to: 'static_pages#about'
	get '/instrucciones',			 to: 'static_pages#instructions'
	
	devise_for :agents, path_names: {
 		sign_in: 'acceder', 
 		sign_out: 'salir', 
 		password: 'contrasena', 
 		confirmation: 'confirmacion', 
 		unlock: 'desbloquear', 
 		registration: 'registro', 
 		sign_up: 'nueva-cuenta'
	}

	authenticate :agent, lambda { |a| a.approved? } do
		mount Sidekiq::Web => 'admin/sidekiq'
	end

	get '/admin', to: redirect('admin/dashboard/index')

	namespace :admin do
		resources :agents, except: [:new, :create]
		resources :business_branches
		resources :businesses do
			member do
				post 'upload_logo'
				delete 'delete_logo'
			end
		end
		resources :coupon_winners
		resources :coupons do
			member do
				get 'preview'
				post 'upload_image'
				delete 'delete_image'
			end
		end
		get 'dashboard/index'
		resources :emails
		resources :emails_sent
		resources :project_updates
		resources :states, except: [:new, :create, :destroy]
		resources :surveys
		resources :surveys_dispensed
		resources :users
	end

	match '*path', to: redirect('/404'), via: :all

end

app/models/admin/surveys_dispensed.rb
class Admin::SurveysDispensed < ActiveRecord::Base
	self.table_name = "surveys_dispensed"
	
	belongs_to :survey
	belongs_to :user

	validates :user_id,
		presence: {
			message: ErrorMsg::MSG[:empty_field]
		},
		numericality: {
			only_integer: true,
			message: ErrorMsg::MSG[:number_digits_positive]
		},
		inclusion: {			
			in: :user_ids,
			message: ErrorMsg::MSG[:invalid_option]
		}

	validates :survey_id,
		presence: {
			message: ErrorMsg::MSG[:empty_field]
		},
		numericality: {
			only_integer: true,
			message: ErrorMsg::MSG[:number_digits_positive]
		},
		inclusion: {			
			in: :survey_ids,
			message: ErrorMsg::MSG[:invalid_option]
		}

	validates :where,
		presence: {
			message: ErrorMsg::MSG[:empty_field]
		}

	def user_ids
		User.all.pluck(:id)
	end

	def survey_ids
		Admin::Survey.all.pluck(:id)
	end

end

app/controllers/admin/surveys_dispensed_controller.rb
class Admin::SurveysDispensedController < ApplicationController

	before_action :authenticate_agent!
	before_action :authorize_agent!
	before_action :set_surveys_dispensed, only: [:show, :edit, :update, :destroy]

	# GET /surveys_dispensed
	# GET /surveys_dispensed.json
	def index
		@surveys_dispensed = Admin::SurveysDispensed.order(:id)
	end

	# GET /surveys_dispensed/1
	# GET /surveys_dispensed/1.json
	def show
	end

	# GET /surveys_dispensed/new
	def new
		@surveys_dispensed = Admin::SurveysDispensed.new
	end

	# GET /surveys_dispensed/1/edit
	def edit
	end

	# POST /surveys_dispensed
	# POST /surveys_dispensed.json
	def create
		@surveys_dispensed = Admin::SurveysDispensed.new(surveys_dispensed_params)

		respond_to do |format|
			if @surveys_dispensed.save
				format.html { redirect_to @surveys_dispensed, notice: 'Surveys dispensed was successfully created.' }
				format.json { render :show, status: :created, location: @surveys_dispensed }
			else
				format.html { render :new }
				format.json { render json: @surveys_dispensed.errors, status: :unprocessable_entity }
			end
		end
	end

	# PATCH/PUT /surveys_dispensed/1
	# PATCH/PUT /surveys_dispensed/1.json
	def update
		respond_to do |format|
			if @surveys_dispensed.update(surveys_dispensed_params)
				format.html { redirect_to @surveys_dispensed, notice: 'Surveys dispensed was successfully updated.' }
				format.json { render :show, status: :ok, location: @surveys_dispensed }
			else
				format.html { render :edit }
				format.json { render json: @surveys_dispensed.errors, status: :unprocessable_entity }
			end
		end
	end

	# DELETE /surveys_dispensed/1
	# DELETE /surveys_dispensed/1.json
	def destroy
		@surveys_dispensed.destroy

		respond_to do |format|
			format.html { redirect_to admin_surveys_dispensed_index_url, notice: 'Surveys dispensed was successfully destroyed.' }
			format.json { head :no_content }
		end
	end

	private
		# Use callbacks to share common setup or constraints between actions.
		def set_surveys_dispensed
			@surveys_dispensed = Admin::SurveysDispensed.where(id: params[:id]).first
			notice = "La encuesta dispensada buscada no se encontró."
			redirect_to(admin_surveys_dispensed_index_url, notice: notice) if @surveys_dispensed.nil?
		end

		# Never trust parameters from the scary internet, only allow the white list through.
		def surveys_dispensed_params
			params.require(:admin_surveys_dispensed).permit(:survey_id, :user_id, :where, :response)
		end
end

app/helpers/admin/surveys_dispensed_helper.rb
module Admin::SurveysDispensedHelper
end

app/views/admin/surveys_dispensed/_form.html.haml
= form_for @surveys_dispensed do |f|
  - if @surveys_dispensed.errors.any?
    #error_explanation
      %h2= "#{pluralize(@surveys_dispensed.errors.count, "error")} prohibited this surveys_dispensed from being saved:"
      %ul
        - @surveys_dispensed.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :survey_id, 'Encuesta'
    = f.text_field :survey_id
  .field
    = f.label :user_id, 'Usuario'
    = f.text_field :user_id
  .field
    = f.label :where, 'Donde Aparece'
    = f.text_field :where
  .field
    = f.label :response, 'Respuesta'
    = f.text_field :response
  .actions
    = f.submit 'Guardar', class: 'button'

app/views/admin/surveys_dispensed/edit.html.haml
= render layout: './admin/admin_base' do
	%h2.title Editar Encuesta Dispensada

	= render 'form'

	= link_to 'Mostrar', edit_admin_surveys_dispensed_path(@surveys_dispensed)
	\|
	= link_to 'Listado', admin_surveys_dispensed_index_path

app/views/admin/surveys_dispensed/index.html.haml
= render layout: './admin/admin_base' do
	%h2.title Listado de Encuestas Dispensadas

	%table
		%thead
			%tr
				%th Id
				%th Encuesta
				%th Usuario
				%th Donde Aparece
				%th Respuesta
				%th
				%th
				%th

		%tbody
			- @surveys_dispensed.each do |surveys_dispensed|
				%tr
					%td= surveys_dispensed.id
					%td= surveys_dispensed.survey_id
					%td= surveys_dispensed.user_id
					%td= surveys_dispensed.where
					%td= surveys_dispensed.response
					%td= link_to 'Mostrar', admin_surveys_dispensed_path(surveys_dispensed)
					%td= link_to 'Editar', edit_admin_surveys_dispensed_path(surveys_dispensed)
					%td= link_to 'Eliminar', admin_surveys_dispensed_path(surveys_dispensed), :method => :delete, :data => { :confirm => '¿Está seguro?' }

	%br

	= link_to 'Dispensar nueva encuesta', new_admin_surveys_dispensed_path

app/views/admin/surveys_dispensed/new.html.haml
= render layout: './admin/admin_base' do
	%h2.title Dispensar Nueva Encuesta

	= render 'form'

	= link_to 'Listado', admin_surveys_dispensed_index_path

app/views/admin/surveys_dispensed/show.html.haml
= render layout: './admin/admin_base' do
	%h2.title Encuesta Dispensada
	%p
		%b Id:
		= @surveys_dispensed.id
	%p
		%b Encuesta:
		= link_to @surveys_dispensed.survey.purpose, 
			admin_survey_path(@surveys_dispensed.survey.id)
	%p
		%b Usuario:
		= link_to @surveys_dispensed.user.email,
			admin_user_path(@surveys_dispensed.user.id)
	%p
		%b Donde Aparece:
		= @surveys_dispensed.where
	%p
		%b Respuesta:
		= @surveys_dispensed.response.to_json

	= link_to 'Editar', edit_admin_surveys_dispensed_path(@surveys_dispensed)
	\|
	= link_to 'Listado', admin_surveys_dispensed_index_path