config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do

	root 'registration#new'

	scope :registro, as: 'registro' do
		get 'nuevo' => 'registration#new'
		get 'exito' => 'registration#success'
		post 'crear' => 'registration#create'
		post 'encuesta' => 'registration#survey'
	end

	scope 'promociones' do
		get 	'/', 					to: 'promotions#index', 		as: 'promotions'
		get 	'/:id', 				to: 'promotions#show', 			as: 'promotion'
		post 	'/:id', 				to: 'promotions#claim'
		get 	'/:id/ganador',	to: 'promotions#winner', 		as: 'promotion_winner'
	end

	scope 'contacto', as: 'contact' do
		get '/', to: 'messages#new'
		post '/', to: 'messages#create'
	end

	get '/preguntas-frecuentes',	 to: 'static_pages#faq'
	get '/terminos',					 to: 'static_pages#site_terms'
	get '/quienes-somos',			 to: 'static_pages#about'
	get '/instrucciones',			 to: 'static_pages#instructions'
	
	devise_for :agents, path_names: {
 		sign_in: 'acceder', 
 		sign_out: 'salir', 
 		password: 'contrasena', 
 		confirmation: 'confirmacion', 
 		unlock: 'desbloquear', 
 		registration: 'registro', 
 		sign_up: 'nueva-cuenta'
	}

	authenticate :agent, lambda { |a| a.approved? } do
		mount Sidekiq::Web => 'admin/sidekiq'
	end

	get '/admin', to: redirect('admin/dashboard/index')

	namespace :admin do
		resources :agents, except: [:new, :create]
		resources :business_branches
		resources :businesses do
			member do
				post 'upload_logo'
				delete 'delete_logo'
			end
		end
		resources :coupon_winners
		resources :coupons do
			member do
				get 'preview'
				post 'upload_image'
				delete 'delete_image'
			end
		end
		get 'dashboard/index'
		resources :emails
		resources :emails_sent
		resources :project_updates
		resources :states, except: [:new, :create, :destroy]
		resources :surveys
		resources :surveys_dispensed
		resources :users
	end

	match '*path', to: redirect('/404'), via: :all

end

app/models/admin/coupon.rb
class Admin::Coupon < ActiveRecord::Base
	self.table_name = "coupons"
	
	belongs_to :business_branch
	belongs_to :business
	has_many :coupon_winners, dependent: :destroy

	TYPE_OF_COUPON_OPT = [
		'sucursal_especifica',
		'todas_las_sucursales'
	]

	validates :business_id,
		presence: {
			message: ErrorMsg::MSG[:empty_field]
		},
		numericality: {
			only_integer: true,
			message: ErrorMsg::MSG[:number_digits_positive]
		},
		inclusion: {			
			in: :business_ids,
			message: ErrorMsg::MSG[:invalid_option]
		}

	validates :business_branch_id,
		presence: {
			message: ErrorMsg::MSG[:empty_field]
		},
		numericality: {
			only_integer: true,
			message: ErrorMsg::MSG[:number_digits_positive]
		},
		inclusion: {
			in: :business_branch_ids,
			message: ErrorMsg::MSG[:invalid_option]
		}

	validates :type_of_coupon,
		presence: {
			message: ErrorMsg::MSG[:empty_field]
		},
		inclusion: {			
			in: TYPE_OF_COUPON_OPT,
			message: ErrorMsg::MSG[:invalid_option]
		}

	validates :publish_active,
		allow_nil: true,
		inclusion: { in: [true, false] }

	validates :publish_start_datetime,
		presence: {
			message: ErrorMsg::MSG[:empty_field]
		}

	validates :publish_end_datetime,
		presence: {
			message: ErrorMsg::MSG[:empty_field]
		}

	validates :valid_start_datetime,
		presence: {
			message: ErrorMsg::MSG[:empty_field]
		}

	validates :valid_end_datetime,
		presence: {
			message: ErrorMsg::MSG[:empty_field]
		}

	validates :title,
		presence: {
			message: ErrorMsg::MSG[:empty_field]
		},
		length: {
			maximum: 254,
			message: ErrorMsg::MSG[:text_too_long]
		}

	validates :description,
		presence: {
			message: ErrorMsg::MSG[:empty_field]
		}

	validates :price_regular,
		presence: {
			message: ErrorMsg::MSG[:empty_field]
		},
		numericality: {
			greater_than: 0,
			message: ErrorMsg::MSG[:number_currency_gr_zero]
		}

	validates :price_promo,
		allow_nil: true,
		numericality: {
			greater_than_or_equal_to: 0,
			message: ErrorMsg::MSG[:number_currency]
		}

	validates :quantity,
		presence: {
			message: ErrorMsg::MSG[:empty_field]
		},
		numericality: {
			only_integer: true,
			greater_than_or_equal_to: 0,
			message: ErrorMsg::MSG[:number_digits_positive]
		}

	validates :available,
		presence: {
			message: ErrorMsg::MSG[:empty_field]
		},
		numericality: {
			only_integer: true,
			greater_than_or_equal_to: 0,
			message: ErrorMsg::MSG[:number_digits_positive],
		}

	validates :conditions,
		presence: {
			message: ErrorMsg::MSG[:empty_field]
		}

	validate(
		:publish_end_datetime_conditions,
		:valid_end_datetime_conditions,
		:exchanged_datetime_conditions,
		:available_conditions,
		:price_promo_conditions
	) 

	def business_ids
		Admin::Business.all.pluck(:id)
	end

	def business_branch_ids 
		Admin::BusinessBranch.where(business_id: business_id).pluck(:id)
	end

	def publish_end_datetime_conditions
		return if publish_end_datetime.nil?
		return if publish_start_datetime.nil?

		if publish_end_datetime <= publish_start_datetime
			errors.add(:publish_end_datetime, ErrorMsg::MSG[:date_end_lt_or_eq_to_start])
		end
	end

	def valid_end_datetime_conditions
		return if valid_end_datetime.nil? or valid_start_datetime.nil? or publish_end_datetime.nil?

		if valid_end_datetime <= valid_start_datetime
			errors.add(:valid_end_datetime, ErrorMsg::MSG[:date_end_lt_or_eq_to_start])
		end

		if valid_end_datetime < publish_end_datetime
			errors.add(:valid_end_datetime, ErrorMsg::MSG[:date_valid_lt_publish])
		end
	end

	def exchanged_datetime_conditions
		return if exchanged_datetime.nil? or valid_start_datetime.nil?

		if exchanged_datetime <= valid_start_datetime
			errors.add(:exchanged_datetime, ErrorMsg::MSG[:date_exchanged_lt_valid_start])
		end
	end

	def available_conditions
		return if available.nil? or quantity.nil?

		if available > quantity
			errors.add(:available, ErrorMsg::MSG[:coupon_availability_out_of_range])
		end
	end

	def price_promo_conditions
		return if price_promo.nil? or price_regular.nil?

		if price_promo >= price_regular
			errors.add(:price_promo, ErrorMsg::MSG[:coupon_price_promo_gt_regular])
		end
	end

end

app/controllers/admin/coupons_controller.rb
class Admin::CouponsController < ApplicationController
	before_action :authenticate_agent!
	before_action :authorize_agent!
	before_action :set_coupon, only: [
		:show, 
		:preview, 
		:edit, 
		:update, 
		:destroy, 
		:upload_image, 
		:delete_image
	]
	before_action :set_business_temp_variables, only: [:show, :new, :edit, :create, :update]


	# GET /coupons
	# GET /coupons.json
	def index
		@coupons = Admin::Coupon.all
	end

	# GET /coupons/1
	# GET /coupons/1.json
	def show
		@image_paths = ImageExplorer.new('promotions', @coupon.id).get_image_paths
	rescue Exception => e
		redirect_to admin_path, notice: e.message
	end

	# GET /coupons/1/preview
	def preview 
		@business_img_path = ImageExplorer.new('businesses', @coupon.business_id)
			.get_image_paths().last
		@coupon_img_paths = ImageExplorer.new('promotions', @coupon.id)
			.get_image_paths()
		@errors = flash[:cw_errors] || {}
	end

	# GET /coupons/new
	def new
		@coupon = Admin::Coupon.new
		@businesses = Admin::Business.order(:name)
	end

	# GET /coupons/1/edit
	def edit
		@businesses = Admin::Business.order(:name)
	end

	# POST /coupons
	# POST /coupons.json
	def create
		@coupon = Admin::Coupon.new coupon_params()

		respond_to do |format|
			if @coupon.save
				format.html { redirect_to @coupon, notice: 'El cupón se creó con éxito.' }
				format.json { render :show, status: :created, location: @coupon }
			else
				format.html { render :new }
				format.json { render json: @coupon.errors, status: :unprocessable_entity }
			end
		end
	end

	# PATCH/PUT /coupons/1
	# PATCH/PUT /coupons/1.json
	def update
		respond_to do |format|
			if @coupon.update(coupon_params)
				format.html { redirect_to @coupon, notice: 'El cupón se actualizó con éxito.' }
				format.json { render :show, status: :ok, location: @coupon }
			else
				format.html { render :edit }
				format.json { render json: @coupon.errors, status: :unprocessable_entity }
			end
		end
	end

	# DELETE /coupons/1
	# DELETE /coupons/1.json
	def destroy
		@coupon.destroy
		respond_to do |format|
			format.html { redirect_to admin_coupons_url, notice: 'El cupón se eliminó con éxito.' }
			format.json { head :no_content }
		end
	end

	# PUT /coupons/1/add_logo
	def upload_image
		@image_io = params[:img]
		@img_explorer = ImageExplorer.new('promotions', @coupon.id)
		extension = nil
		last_file_name = nil
		next_file_name = nil
		notice = ''

		# check for correct @image_io type
		unless @image_io.respond_to? :original_filename
			e = RuntimeError.new("@image_io '#{@image_io}' doesn't respond to :original_filename")
			ExceptionHandler.log(e, :error, __FILE__, __LINE__)
			notice = "Hubo un error al procesar la imagen."
			redirect_to(@coupon, notice: notice) and return
		end

		# process @image_io and attempt to upload the image
		begin
			extension = @image_io.original_filename.split('.').last.downcase
			last_file_name = @img_explorer.get_image_file_names().last
			next_file_name = gallery_next_img_file_name(last_file_name, extension)
			@img_explorer.upload_image(next_file_name, @image_io)
		rescue Exception => e
			ExceptionHandler.log(e, :fatal, __FILE__, __LINE__)
			redirect_to(@coupon, notice: e.message) and return
		end

		# happy path redirection
		redirect_to @coupon, notice: 'La imagen se agregó con éxito.'
	end	

	# DELETE /coupons/1/delete_logo
	def delete_image
		@img_explorer = ImageExplorer.new('promotions', @coupon.id)

		begin
			@img_explorer.delete_image(params[:file])
		rescue Exception => e
			ExceptionHandler.log(e, :fatal, __FILE__, __LINE__)
			redirect_to(@coupon, notice: e.message) and return
		end

		redirect_to @coupon, notice: 'La imagen se eliminó con éxito'
	end

	private

		# Never trust parameters from the scary internet, only allow the white list through.
		def coupon_params
			params.require(:admin_coupon).permit(
				:business_id,
				:business_branch_id,
				:type_of_coupon,
				:publish_active,
				:publish_start_datetime,
				:publish_end_datetime,
				:valid_start_datetime,
				:valid_end_datetime,
				:exchanged_datetime,
				:status,
				:title,
				:description,
				:price_regular,
				:price_promo,
				:quantity,
				:available,
				:conditions
			)
		end

		# Use callbacks to share common setup or constraints between actions.
		def set_coupon
			@coupon = Admin::Coupon.where(id: params[:id]).first
			notice = "El cupón buscado no se encontró."
			redirect_to(admin_coupons_url, notice: notice) if @coupon.nil?
		end

		def set_business_temp_variables 
			@business_temp = set_business_temp()
			@branches = set_branches()
			@branches_short_address = set_branches_short_address()
		end

		def set_business_temp
			if params[:admin_coupon].present? and @coupon.nil?
				@coupon = Admin::Coupon.new coupon_params
			else
				@coupon ||= Admin::Coupon.new
			end

			if params[:coupon_business_id]
				return Admin::Business.where(id: params[:coupon_business_id]).first || {}
			elsif @coupon.business_id? and params[:coupon_business_id].nil?
				return Admin::Business.where(id: @coupon.business_id).first || {}
			else
				return {}
			end
		end

		def set_branches
			if @business_temp.present?
				return Admin::BusinessBranch.where(business_id: @business_temp.id) || {}
			elsif @coupon.persisted?
				return Admin::BusinessBranch.where(business_id: @coupon.business_branch_id) || {}
			else
				return {}
			end
		end

		def set_branches_short_address 
			if @branches.present?
				return @branches.map do |branch|
					address = branch.street_name + ' ' + branch.street_no
					address += ' int. ' + branch.inner_no if branch.inner_no?
					address += ', ' + branch.borough + ', ' + branch.city
					[address, branch.id]
				end
			else
				return []
			end
		end

		def gallery_next_img_file_name(last_file_name, extension) 
			file_name = ''

			case last_file_name
			when nil
				file_name = "cupon_#{@coupon.id}_1.#{extension}"
			else
				next_number = last_file_name.match(/_\d+\./).to_s[1..-2].to_i + 1
				file_name = "cupon_#{@coupon.id}_#{next_number}.#{extension}"
			end

			return file_name
		end

end

app/helpers/admin/coupons_helper.rb
module Admin::CouponsHelper

	def print_images_from_paths(image_paths, tag, coupon)
		raise TypeError, "image_paths is not a collection" unless image_paths.respond_to? :each_with_index
		raise TypeError, "tag not of type String or Symbol" unless tag.respond_to? :to_sym
		raise TypeError, "coupon is not of type Admin::Coupon" if coupon.class != Admin::Coupon

		image_paths.each_with_index do |path, index|
			haml_tag(tag.to_sym) do
				haml_tag :span, "#{index + 1})"
				haml_concat(link_to image_tag(path, size: '200x200'), root_url + 'images/' + path)
				haml_tag :span, 
					"Tamaño: #{number_to_human_size(File.size "public/images/" + path)}"
				img_file_name = path.split('/').last
				haml_concat(
					link_to 'Eliminar', 
					delete_image_admin_coupon_path(coupon.id, file: img_file_name), 
					method: :delete
				)
			end
		end
	end

	def form_select_for_business(form) 
		return if @businesses.nil?

		businesses_list = @businesses.map {|b| [b.name, b.id]}
		@options = {
			selected: params[:coupon_business_id],
			include_blank: true
		}

		if @coupon.business_id? and params[:coupon_business_id].nil?
			@options[:selected] = @coupon.business_id
		end

		return form.select :business_id, businesses_list, @options
	end

end

app/views/admin/coupons/_form.html.haml
= form_for @coupon do |f|
	.row
		.column.medium-12
			- if @coupon.errors.any?
				#error_explanation
					%h2= "#{pluralize(@coupon.errors.count, "error")} prohibited this coupon from being saved:"
					%ul
						- @coupon.errors.full_messages.each do |msg|
							%li= msg
	.row
		.column.medium-9
			.field
				= f.label :business_id, 'Negocio'
				= form_select_for_business(f)
		.column.medium-3
			.field
				= f.label :type_of_coupon, 'Tipo de Cupón'
				- options = Admin::Coupon::TYPE_OF_COUPON_OPT.each { |opt| [opt] }
				= f.select :type_of_coupon, options, include_blank: true
		.column.medium-12
			.field
				= f.label :business_branch_id, 'Sucursal'
				= f.select :business_branch_id, @branches_short_address, include_blank: true
			.field
				= f.label :title, 'Título'
				= f.text_field :title
			%br/
		.column.medium-6
			.row
				.column.medium-10
					%p.text-center Precio
				.column.medium-2.end
			.row
				.column.medium-5
					.field
						= f.label :price_regular, 'Regular'
						= f.text_field :price_regular
				.column.medium-5
					.field
						= f.label :price_promo, 'Promocional'
						= f.text_field :price_promo
				.column.medium-2.end
		.column.medium-6
			.row
				.column.medium-offset-2.medium-10
					%p.text-center Cupones
				.column.medium-offset-2.medium-5
					.field
						= f.label :quantity, 'Liberados'
						= f.number_field :quantity
				.column.medium-5
					.field
						= f.label :available, 'Disponibles'
						= f.number_field :available
		.column.medium-12
			.field
				= f.label :description, 'Descripción'
				= f.text_area :description, rows: 7
		.column.medium-12
			.field
				= f.label :conditions, 'Condiciones'
				= f.text_area :conditions, rows: 7
		.column-medium-12
			.row
				.column.medium-12
					%br/
				.column.medium-4
					%p ¿Activo para ser publicado?
				.column.medium-1
					= 'Si'
					= f.radio_button :publish_active, 'true'
				.column.medium-7
					= 'No'
					= f.radio_button :publish_active, 'false'
				.column.medium-10.end
		.column.medium-12
			%br/
			%p Periodo de Publicación
		- dt_now = DateTime.now
		.column.medium-11.medium-offset-1
			.select_datetime
				= f.label :publish_start_datetime, 'Inicio'
				= f.datetime_select :publish_start_datetime, start_year: 2016, default: dt_now
		.column.medium-11.medium-offset-1
			.select_datetime
				= f.label :publish_end_datetime, 'Fin'
				= f.datetime_select :publish_end_datetime, start_year: 2016, default: dt_now + 7.days
		.column.medium-12
			%br/
			%p Periodo de Validez
		.column.medium-11.medium-offset-1
			.select_datetime
				= f.label :valid_start_datetime, 'Inicio'
				= f.datetime_select :valid_start_datetime, start_year: 2016, default: dt_now
		.column.medium-11.medium-offset-1
			.select_datetime
				= f.label :valid_end_datetime, 'Fin'
				= f.datetime_select :valid_end_datetime, start_year: 2016, default: dt_now + 2.months
		.column.medium-12
			%br/
			.select_datetime
				= f.label :exchanged_datetime, 'Fecha canjeado'
				= f.datetime_select :exchanged_datetime, start_year: 2016, prompt: true
		.column.medium-12
			%br/
			%br/
			.actions
				= f.submit 'Guardar', class: 'button'

app/views/admin/coupons/edit.html.haml
= render layout: './admin/admin_base' do
	%h2.title Editar Cupón

	= render 'form'

	= link_to 'Mostrar', @coupon
	\|
	= link_to 'Listado', admin_coupons_path

app/views/admin/coupons/index.html.haml
= render layout: './admin/admin_base' do
	%h1.title Listado de Cupones

	%table
		%thead
			%tr
				%th Id
				%th Negocio
				%th Título
				%th Cant.
				%th Disp.
				%th 
				%th 
				%th 

		%tbody
			- @coupons.each do |coupon|
				%tr
					%td= coupon.id
					%td= link_to (coupon.business_branch.business.name), 
						admin_business_path(coupon.business_branch.business_id)
					%td= coupon.title
					%td= coupon.quantity
					%td= coupon.available
					%td= link_to 'Mostrar', admin_coupon_path(coupon['id'])
					%td= link_to 'Editar', edit_admin_coupon_path(coupon['id'])
					%td= link_to 'Eliminar', admin_coupon_path(coupon['id']), :method => :delete, :data => { :confirm => '¿Estás seguro?' }

	%br

	= link_to 'Nuevo Cupón', new_admin_coupon_path

app/views/admin/coupons/new.html.haml
= render layout: './admin/admin_base' do
	%h2.title Nuevo Cupón

	= render 'form'

	= link_to 'Listado', admin_coupons_path

app/views/admin/coupons/preview.html.haml
.wide-ribbon
	.row
		.column.medium-12
			%ul.new-sub-nav
				%li ACCIONES:
				%li
					%a{href: admin_coupon_path(@coupon.id)} Regresar

.row
	.column.medium-12
		- @promotion = @coupon
		- @promotion_img_paths = ImageExplorer.new('promotions', @promotion.id).get_image_paths()
		= render partial: '/promotions/show_layout_1'

app/views/admin/coupons/show.html.haml
= render layout: './admin/admin_base' do
	%h2.title Cupón
	
	%ul.new-sub-nav
		%li ACCIONES:
		%li
			=link_to 'Previsualizar', preview_admin_coupon_path(@coupon.id)
		%li
			= link_to 'Visitar', promotion_path(@coupon.id), target: '_blank'
		%li
			= link_to 'Editar', edit_admin_coupon_path(@coupon)
	%br/
	
	%p
		%b Id:
		= @coupon.id
	%p
		%b Negocio:
		= link_to @coupon.business.name, admin_business_path(@coupon.business_id)
	%p
		%b Sucursal:
		- branch = Admin::BusinessBranch.find(@coupon.business_branch_id)
		- short_address = "#{branch.street_name}, #{branch.city}, #{branch.state.name}"
		= link_to short_address, admin_business_branch_path(branch.id)
	%p
		%b Tipo de Cupón:
		= @coupon.type_of_coupon
	%p
		%b Título:
		= @coupon.title

	%b Foto(s) del producto:
	%ul.print-files
		- print_images_from_paths(@image_paths, 'li', @coupon)
		.multiple-uploads
			= form_tag({action: :upload_image, id: @coupon.id}, multipart: true) do
				%span
					= file_field_tag 'img', accept: 'image/png, image/jpeg'
					= submit_tag 'Subir Imagen'
	%p
		%b Cantidad:
		= @coupon.quantity
	%p
		%b Disponible:
		= @coupon.available
	%p
		%b Precio Regular:
		= number_to_currency @coupon.price_regular
	%p
		%b Precio Promocional:
		= number_to_currency @coupon.price_promo
	%p
		%b Estatus:
		= @coupon.status
	%p
		%b ¿Activo para ser publicado?
		- resp = @coupon.publish_active
		- if resp == true
			= 'Si'
		- if resp == false or resp == nil
			= 'No'

	%b Fecha de publicación:
	%ul
		%li
			= 'Inicio:'
			= format_datetime @coupon.publish_start_datetime
		%li
			= 'Fin:'
			= format_datetime @coupon.publish_end_datetime

	%b Fecha de validez:
	%ul
		%li
			= 'Inicio:'
			= format_datetime @coupon.valid_start_datetime
		%li
			= 'Fin:'
			= format_datetime @coupon.valid_end_datetime

	%p
		%b Fecha canjeado:
		- exchanged = @coupon.exchanged_datetime
		= exchanged ? format_datetime(exchanged) : 'Aún no'

	%b Descripción:
	- haml_tag :ul do
		- wrap_lines_with_tag(@coupon.description, 'li')

	%b Condiciones:
	- haml_tag :ul do
		- wrap_lines_with_tag(@coupon.conditions, 'li')